<?php

/**
 * My Application bootstrap file.
 */
use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;
use Nette\Application\Routers\Route;


// Load Nette Framework or autoloader generated by Composer
require LIBS_DIR . '/autoload.php';


// Configure application
$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode($configurator::AUTO);
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(APP_DIR)
	->addDirectory(LIBS_DIR)
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon', FALSE)
	->addConfig(__DIR__ . '/config/config.local.neon', FALSE);
$container = $configurator->createContainer();

// Setup router
$container->router[] = new Route('index.php', 'Front:Homepage:default', Route::ONE_WAY);
$container->router[] = new Route('admin/<presenter>/<action>[/<id>]', array(
	'module' => 'Admin',
	'presenter' => 'Homepage',
	'action' => 'default',
));
$container->router[] = new Route('<presenter>/<action>[/<id>]', array(
	'module' => 'Front',
	'presenter' => 'Homepage',
	'action' => 'default',
));

// Doctrine EM
$paths = array(__DIR__ . '/model');
$isDevMode = TRUE;

$config = Setup::createAnnotationMetadataConfiguration($paths, $isDevMode);
$em = EntityManager::create($container->parameters['database'], $config);

$container->addService('em', $em);

// Configure and run the application!
if (!defined('CONSOLE')) {
	$container->application->run();
}
